[package]
name = "table_program"
version = "0.1.0"
authors = ["Najam-ul-islam <najam.capricon88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_table = {path = "my_table"}